---
title: "Cardio Vascular Disease Project"
author: "Team 1: Afif Mahmassani, Turner Luo, Lijia Ren, Steven Tian"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
library(ezids)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
```

## Summary of the dataset   
### Load the dataset   
```{r}
cardio_vascular_disease <- read.csv2("cardio_train.csv", header = TRUE)
str(cardio_vascular_disease)
```
Noticed some of the variables should be factor.    
```{r}
cardio <- cardio_vascular_disease
cardio$gender <- factor(cardio_vascular_disease$gender)
cardio$smoke <- factor(cardio_vascular_disease$smoke)
cardio$alco <- factor(cardio_vascular_disease$alco)
cardio$active <- factor(cardio_vascular_disease$active)
cardio$cardio <- factor(cardio_vascular_disease$cardio)
cardio$weight <- as.integer(cardio_vascular_disease$weight)
str(cardio)
```
```{r, results='markup'}
xkablesummary(cardio[,2:13], title = "Summary of Cardio Vascular Disease Data")
```

