---
title: "Cardio Vascular Disease Project"
author: "Team 1: Afif Mahmassani, Turner Luo, Lijia Ren, Steven Tian"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
library(ezids)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
```

```{r}
cardio_vascular_disease <- read.csv2("cardio_train.csv", header = TRUE)
str(cardio_vascular_disease)
```

```{r}
df <- cardio_vascular_disease
df$id <- NULL
df$gender <- factor(cardio_vascular_disease$gender)
df$smoke <- factor(cardio_vascular_disease$smoke)
df$alco <- factor(cardio_vascular_disease$alco)
df$active <- factor(cardio_vascular_disease$active)
df$cardio <- factor(cardio_vascular_disease$cardio)
df$cholesterol <- factor(cardio_vascular_disease$cholesterol)
df$gluc <- factor(cardio_vascular_disease$gluc)
df$weight <- as.integer(cardio_vascular_disease$weight)

levels(df$cardio) <- c("No", "Yes")
levels(df$gender) <- c("Female", "Male")
levels(df$cholesterol) <- c("Normal", "Above Normal", "Well Above Normal")
levels(df$gluc) <- c("Normal", "Above Normal", "Well Above Normal")
levels(df$smoke) <- c("No", "Yes")
levels(df$alco) <- c("No", "Yes")
levels(df$active) <- c("No", "Yes")
df <- na.omit(df)

str(df)
``` 

```{r}
df_num <- df
for(i in 1:12){
  if (!(i %in% c(1,3:6))){
    df_num[,i] = as.numeric(df_num[,i])
  }
}
str(df_num)
```

```{r}
#convert variables to numeric
scale1 <- subset(df_num, select = -cardio)
scale1$cardio <- df$cardio
str(scale1)
scale1[c(1,3,4,5,6)] <- as.data.frame(scale(scale1[c(1,3,4,5,6)], center = TRUE, scale = TRUE))
set.seed(1)
df_sample <- sample(2, nrow(scale1), replace = TRUE, prob = c(0.75,0.25))
df_train <- scale1[df_sample==1, 1:11]
df_test <- scale1[df_sample==2, 1:11]
df.trainLabels <- df[df_sample==1, 12]
df.testLabels <- df[df_sample==2, 12]
str(df_train)
str(df_test)
```

```{r, echo=FALSE}
loadPkg("class")
chooseK = function(k, train_set, val_set, train_class, val_class){
  
  # Build knn with k neighbors considered.
  set.seed(1)
  class_knn = knn(train = train_set,    #<- training set cases
                  test = val_set,       #<- test set cases
                  cl = train_class,     #<- category for classification
                  k = k) #,                #<- number of neighbors considered
                  # use.all = TRUE)       #<- control ties between class assignments. If true, all distances equal to the k-th largest are included
  
  tab = table(class_knn, val_class)
  #cm = confusionMatrix(class_knn, reference = cus_test_y ) # from caret library
  # print.confusionMatrix(cm)
  # 
  #cmaccu = cm$overall['Accuracy']
  
  # Calculate the accuracy.
  accu = sum(tab[row(tab) == col(tab)]) / sum(tab)                         
  cbind(k = k, accuracy = accu)
}
```

```{r, results='markup'}
knn_different_k = sapply(seq(1, 21, by = 2),  
                         function(x) chooseK(x, 
                                             train_set = df_train,
                                             val_set = df_test,
                                             train_class = df.trainLabels,
                                             val_class = df.testLabels))
knn_different_k = data.frame(k = knn_different_k[1,],
                             accuracy = knn_different_k[2,])
library("ggplot2")
ggplot(knn_different_k,
       aes(x = k, y = accuracy)) +
  geom_line(color = "orange", size = 1.5) +
  geom_point(size = 3) + 
  labs(title = "accuracy vs k")

xkabledply((knn_different_k))
```
`k=17` is a decent choice.
```{r, results='markup'}
pred <- knn(train = df_train, test = df_test, cl=df.trainLabels, k=17)
pred

loadPkg("gmodels")
churnPredCross <- CrossTable(df.testLabels, pred, prop.chisq = FALSE)
```
accuracy = 0.6648     
precision = 0.6809    
recall = 0.6348     
specificity = 0.6954        
F1_score = 0.657      

### KNN with selected variables    
Remove `gender` and `gluc`.   
```{r}
df_num2 <- subset(df_num, select = -c(gender, gluc, prob))
str(df_num2)
scale2 <- df_num2
scale2[1:5] <- scale(df_num2[1:5], center = TRUE, scale = TRUE)
scale2$cardio <- df$cardio
str(scale2)
```

```{r}
set.seed(1)
df_sample2 <- sample(2, nrow(scale2), replace = TRUE, prob = c(0.75,0.25))
df_train2 <- scale2[df_sample2==1, 1:9]
df_test2 <- scale2[df_sample2==2, 1:9]
df.trainLabel2 <- scale2[df_sample2==1, 10]
df.testLabel2 <- scale2[df_sample2==2, 10]
```

### Select K    
```{r, results='markup'}
knn_different_k2 = sapply(seq(1, 21, by = 2),  
                         function(x) chooseK(x, 
                                             train_set = df_train2,
                                             val_set = df_test2,
                                             train_class = df.trainLabel2,
                                             val_class = df.testLabel2))
str(knn_different_k2)
knn_different_k2 = data.frame(k = knn_different_k2[1,],
                             accuracy = knn_different_k2[2,])
library("ggplot2")
ggplot(knn_different_k2,
       aes(x = k, y = accuracy)) +
  geom_line(color = "orange", size = 1.5) +
  geom_point(size = 3) + 
  labs(title = "accuracy vs k")
xkabledply((knn_different_k2))
```

We should better select value `k=13` here as it has the highest accuracy.  
```{r}
pred2 <- knn(train = df_train2, test = df_test2, cl = df.trainLabel2, k = 13)
knn.roc.prob <- attr(knn(train = df_train2, test = df_test2, cl = df.trainLabel2, k = 13, prob = T), 'prob')
pred2
```

```{r, results='markup'}
churnPredCross2 <- CrossTable(df.testLabel2, pred2, prop.chisq = FALSE)
```

accuracy = 0.6717
precision = 0.6877
recall = 0.6432
specificity = 0.701
F1_score = 0.6616

#Comparison
```{r, results='markup'}
tab <- matrix(c(0.6583, 0.6733, 0.6308, 0.6866, 0.6514, 0.6717, 0.6877, 0.6432, 0.701, 0.6616, 0.722, 0.743, 0.677, 0.767, 0.708), ncol = 5, byrow = TRUE)
colnames(tab) <- c("Accuracy", "Precision", "Recall", "Specificity", "F1 Score")
rownames(tab) <- c("KNN with all variables", "KNN with selected variables", "Logistic with selected variables")
tab <- as.table(tab)
xkabledply(tab, "Models Comparison")
```